import "./globals.css";

import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`bg-zinc-100 font-sans antialiased ${vazirmatn.variable}`}>
        <div className="mx-auto flex min-h-screen w-full max-w-prose flex-col items-center gap-10">
          {children}

          <footer className="mx-auto flex h-5 w-fit items-center justify-center border border-b-0 border-zinc-300 px-3 pt-1">
            <a href="https://www.haashemi.dev/" target="_blank" rel="noreferrer" className="text-xs text-zinc-800">
              haashemi.dev
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
