import "./globals.css";

import type { Metadata } from "next";

import { Vazirmatn } from "next/font/google";
import Link from "next/link";

import { NProgressBar } from "./_components/progress-bar-provider";

const vazirmatn = Vazirmatn({
  subsets: ["arabic", "latin"],
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html dir="rtl" lang="fa">
      <body className={`bg-zinc-100 font-sans antialiased ${vazirmatn.variable}`}>
        <div className="mx-auto flex min-h-screen w-full max-w-prose flex-col items-center gap-10">
          <header className="flex h-20 w-full items-center justify-between border border-t-0 border-zinc-300 px-3">
            <Link className="text-3xl font-black" href="/">
              بلاگی
            </Link>
            <Link className="bg-black px-4 py-2 text-sm text-white" href="/auth/sign-in">
              ورود / ثبت‌نام
            </Link>
          </header>

          {children}

          <footer className="mx-auto flex h-5 w-fit items-center justify-center border border-b-0 border-zinc-300 px-3 pt-1">
            <a className="text-xs text-zinc-800" href="https://www.haashemi.dev/" rel="noreferrer" target="_blank">
              haashemi.dev
            </a>
          </footer>
        </div>

        <NProgressBar />
      </body>
    </html>
  );
}
