name: blogi

services:
  backend:
    container_name: blogi-backend
    build:
      context: ./backend
    networks:
      - back-tier
      - front-tier
    ports:
      - 5676:8080
    volumes:
      - .env:/app/.env
    restart: always

  website:
    container_name: aka-website
    build:
      context: ./website
      args:
        - WEB_APP_HOST=${WEB_APP_HOST}
        - NEXT_PUBLIC_DASHBOARD_API_URL=${NEXT_PUBLIC_DASHBOARD_API_URL}
    env_file: .env
    networks:
      - front-tier
    ports:
      - 5677:3000
    restart: always

  postgres:
    container_name: aka-postgres
    image: postgres:16
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=blogi
      - POSTGRES_PASSWORD=p17mZ0D7NT7lQi6j
    networks:
      - back-tier
    restart: always
    shm_size: 128mb

networks:
  back-tier:
  front-tier:
